import { FLAGS, MODULE_ID, SETTINGS } from "./constants.js";
import { buildPrototypePlan } from "./generation/prototype-generator.js";
import { commitPrototypePlan, isGeneratedScene } from "./adapters/foundry-scene-adapter.js";
import { getCompatibilityReport } from "./integrations/compatibility.js";
import { getEncounterTimeContext } from "./integrations/seasons-stars-adapter.js";
import { getMidiQolCapabilities } from "./integrations/midi-qol-adapter.js";

let lastGeneratedSceneUuid = null;
let lastExplorationSceneUuid = null;

export const api = Object.freeze({
  getCompatibilityReport,
  getEncounterTimeContext,
  getMidiQolCapabilities,
  async generatePrototype({
    seed = `manual::${Date.now()}`,
    cellKey = "manual",
    sourceSceneUuid = canvas.scene?.uuid ?? lastExplorationSceneUuid,
    activate = false
  } = {}) {
    if (!sourceSceneUuid) {
      throw new Error("No source Scene UUID available. Activate a Scene or pass sourceSceneUuid.");
    }

    const plan = buildPrototypePlan({
      seed,
      cellKey,
      sourceSceneUuid,
      widthCells: Number(game.settings.get(MODULE_ID, SETTINGS.PROTOTYPE_WIDTH_CELLS)),
      heightCells: Number(game.settings.get(MODULE_ID, SETTINGS.PROTOTYPE_HEIGHT_CELLS))
    });
    const scene = await commitPrototypePlan(plan, { activate });
    lastGeneratedSceneUuid = scene.uuid;
    lastExplorationSceneUuid = sourceSceneUuid;
    return { scene, plan };
  },

  async returnToExploration(sceneUuid = lastExplorationSceneUuid ?? canvas.scene?.uuid) {
    const scene = await fromUuid(sceneUuid);
    if (!scene || scene.documentName !== "Scene") {
      throw new Error("Exploration Scene UUID is invalid.");
    }
    return scene.activate();
  },

  async deleteGeneratedScene(sceneUuid = lastGeneratedSceneUuid ?? canvas.scene?.uuid) {
    const scene = await fromUuid(sceneUuid);
    if (!scene || scene.documentName !== "Scene") throw new Error("Scene not found.");
    if (!isGeneratedScene(scene)) {
      throw new Error("Refusing to delete a Scene not tagged as generated by this module.");
    }

    const manifest = scene.getFlag(MODULE_ID, FLAGS.MANIFEST);
    if (manifest?.source?.explorationSceneUuid === scene.uuid) {
      throw new Error("Refusing to delete the source exploration Scene.");
    }

    await scene.delete();
    if (lastGeneratedSceneUuid === sceneUuid) lastGeneratedSceneUuid = null;
    return true;
  },

  rememberExplorationScene(sceneUuid) {
    lastExplorationSceneUuid = sceneUuid;
  }
});
